KeywordList =
{
	"GodBoon",
	"GodBoonPlural",
	"PomPlural",
	"Rarity",
	"ChallengeSwitch",
	"ShrinePointGate",
	"HealthGate",
	"HealthGatePlural",
	"Fountain",
	"FountainPlural",
	"Keepsakes",
	"Decor",
	"Cosmetic",
	"QuestItem",
	"LimitedItem",
	"HouseRepair",
	"NewSystem",
	"MusicSheet",
	"RunUpgrade",
	"NewChamber",
	"KeyItem",
	"UISkin",
	"PactExtension",
	"PassiveItem",
	"InstantItem",
	"Room",
	"RoomAlt",
	"Encounter",
	"EncounterAlt",
	"EncounterPlural",
	"Boss",
	"BossPlural",
	"SelfDamage",
	"FishingPoint",

	"Invulnerable",
	"Invisible",
	"GreaterInvisible",
	"Crit",
	"Armor",
	"Sturdy",
	"KReload",
	"ManualReload",
	"DeathWeapon",
	"Vulnerable",
	"Revenge",

	"Weak",
	"Curse",
	"Charm",
	"Rupture",
	"Stagger",
	"Mark",
	"Static",
	"Poison",
	"Chill",

	"GodMode",

	"WillReplace",

	-- Characters
	"Orpheus",
	"Sisyphus",
	"Nyx",
	"Thanatos",
	"Achilles",

	-- Weapon Aspects
	"AchillesAspect",
	"HadesAspect",
	"ZeusAspect",
	"HestiaAspect",
	"ChironAspect",
	"TalosAspect",
	"GuanYuAspect",
	"ArthurAspect",
	"ArthurSpecial",
	"RamaAspect",
	"RamaSpecial",
	"BeowulfAspect",
	"BeowulfTackle",
	"BeowulfCast",
	"HeraCast",
	"LuciferAspect",
	"LuciferSpecial",
	"GilgameshAspect",
	"GilgameshDash",
	"GilgameshSpecial",

	-- MetaUpgrade Screen Actions
	"MetaUpgradeUnlock",
	"MetaUpgradeSwap",
	"MetaUpgradeRefund",

	-- MetaUpgrades
	"MoveSpeed",
	"HealthDrop",
	"RareBoonChance",
	"EpicBoonChance",
	"Reroll",
	"DashCharges",
	"DashAttack",
	"EffectVulnerability",
	"AmmoVulnerability",
	"ExtraChance",
	"ExtraChanceAlt",
	"ExtraChanceChaos",
	"Rally",
	"AmmoSupply",
	"SneakAttack",
	"StartingHealth",
	"StartingMoney",
	"HealthEncounterEndRegen",
	"DoorHeal",
	-- B-Side MetaUpgrades
	"AlphaAttack",
	"DarknessHeal",
	"ExtraChanceWrath",
	"ExtraChanceReplenish",
	"PerfectDash",
	"UnstoredAmmoVulnerability",
	"AmmoReload",
	"InterestMoney",
	"HighHealthDamage",
	"GodEnhancement",
	"DuoRarityBoonChance",
	"RunRewardBonusChance",
	"StoredAmmoSlow",
	"HeroicBoonChance",
	"RerollPanel",
	-- Shrine
	"DarknessCap",
	"HealingReduction",
	"HealingReduction_Total",
	"EnemyHealth",
	"EnemyDamage",
	"TrapDamage",
	"NoInvulnerability",
	"EnemySpeed",
	"EnemyShield",
	"EnemyCount",
	"EnemyElite",
	"MinibossCount",
	"ReducedLootChoices",
	"ShopPrices",
	"ForceSell",
	"BossDifficulty",
	"HardEncounter",
	"BiomeSpeed",
	"LockedChoice",
	"Thermometer",
	-- Misc. MetaUpgrade
	"MetaUpgradeRerollBlockedDescription",
	"MetaUpgradeRerollDescription",
	"Sealed",
	"GodEnhancement_InRun",

	"Attack",
	"AttackPlural",
	"Dash",
	"Cast",
	"CastPlural",
	"CastAlt",
	"Special",
	"Wrath",
	"WrathDerivedStocks",
	"WrathGauge",
	"WrathHades",
	"EXWrath",
	"PowerShot",
	"PowerCharge",
	"PowerFlurry",
	"Surge",
	"Status",
	"Assist",

	"BlinkStrike",
	"BlinkSpecial",
	"Spin",
	"GuanYuSpin",
	"Tackle",
	"Thrust",
	"Slash",
	"Retrieve",
	"RapidFire",
	"ForceNova",
	"Dodge",

	"Deflect",
	"BladeRift",
	"Wine",
	"Cloud",
	"Traps",

	"Common",
	"Rare",
	"Epic",
	"Heroic",
	"Legendary",
	"Duo",
}